### ISSUE TITLE
Place the plots above the code

### ISSUE THREAD

**Issue by IanButterworth** [MakieOrg/BeautifulMakie#44]
I think it would make more sense for the purpose of browsing

**Comment by lazarusA** [comment]
agree, I will do it like this:

<img width="1248" alt="Screenshot 2024-01-06 at 18 11 10" src="https://github.com/MakieOrg/BeautifulMakie/assets/19525261/b6f9f1da-f8d9-468e-b0d7-d8f9d0c168ca">
